version: "3"

services:
    web:
        build: ./web
        restart: unless-stopped
        ports:
            - 3000:3000
        env_file:
            - ./secrets.env
    discord:
        build: ./discord
        # restart: unless-stopped
        env_file:
            - ./secrets.env
        links:
            - 'web'
